name: Build Windows Version

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat

      - name: Install Qt using vcpkg
        run: |
          .\vcpkg\vcpkg install qt5

      - name: Build the project
        run: |
          echo "Building the project"
          cd build/general/qtcreator
          qmake sokit.pro
          nmake

      - name: Archive the output
        run: |
          echo "Archiving the output"
          Compress-Archive -Path bin\debug\* -DestinationPath output.zip
