name: Build Windows Version

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        run: |
          echo "Installing Qt"
          choco install qt --params="'/NoDesktop'" # 不指定版本，安装最新版本

      - name: Build the project
        run: |
          echo "Building the project"
          set PATH=%PATH%;C:\Program Files\Qt\5.15.16\msvc2019_64\bin  # 更新为正确的 Qt 版本路径
          cd build/general/qtcreator
          qmake sokit.pro
          nmake

      - name: Archive the output
        run: |
          echo "Archiving the output"
          Compress-Archive -Path bin\debug\* -DestinationPath output.zip
