name: Build Windows Version

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          ./vcpkg install qt5 > vcpkg_install_log.txt
          echo "vcpkg install log:"  
          cat vcpkg_install_log.txt
          echo "Checking for qmake in vcpkg installed directory..."
          $qtPath = "D:\a\sokit\sokit\vcpkg\installed\x64-windows\tools\qt5\bin"
          if (Test-Path "$qtPath\qmake.exe") {
            echo "qmake found at $qtPath\qmake.exe"
            $env:PATH += ";$qtPath"
          } else {
            echo "qmake not found in the expected vcpkg path."
          }
          echo "Listing vcpkg directory contents:"
          dir D:\a\sokit\sokit\vcpkg\installed\x64-windows\tools\qt5\bin

      - name: Setup Visual Studio Environment
        run: |
          echo "Setting up Visual Studio environment"
          & "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

      - name: Build the project
        run: |
          echo "Building the project"
          $env:PATH += ";D:\a\sokit\sokit\vcpkg\installed\x64-windows\bin"  # 更新为 vcpkg 的 Qt 安装路径
          cd build/general/qtcreator
          echo "Current PATH: $env:PATH"
          echo "Attempting to locate qmake..."
          D:\a\sokit\sokit\vcpkg\installed\x64-windows\tools\qt5\bin\qmake.exe sokit.pro
          nmake

      - name: Archive the output
        run: |
          echo "Archiving the output"
          Compress-Archive -Path bin\debug\* -DestinationPath output.zip
